//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manifest
    {
        public int ManifestID { get; set; }
        public int TicketNum { get; set; }
        public int FlightNum { get; set; }
        public int TransactionNum { get; set; }
    
        public virtual FlightInfo FlightInfo { get; set; }
        public virtual PassengerInfo PassengerInfo { get; set; }
        public virtual PaymentInfo PaymentInfo { get; set; }
    }
}
