//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject.Models
{
    using System;
    using System.Collections.Generic;
     using System.ComponentModel.DataAnnotations;

     public partial class PaymentInfo
    {
        [Display (Name = "Transaction Number")]
        public int TransactionNum { get; set; }
        [Display (Name = "First Name")]
        public string FirstName { get; set; }
        [Display (Name = "Last Name")]
        public string LastName { get; set; }
        [Display (Name = "Security Code")]
        public int SecurityCode { get; set; }
        [Display (Name = "Expiration Date")]
        public System.DateTime ExpirationDate { get; set; }
        [Display (Name = "Total Cost")]
        public decimal TotalCost { get; set; }
        [Display (Name = "Card Number")]
        public int CradNum { get; set; }
        [Display (Name = "Manifest Id")]
        public int ManifestID { get; set; }
    
        public virtual Manifest Manifest { get; set; }
    }
}
